### ISSUE TITLE
Ability to reliably process messages?

### ISSUE THREAD

**Issue by mmcgrana** [wvanbergen/kafka#13]
First of all, thanks for writing and sharing this library! It looks like a promising
option for writing multi-node Kafka consumers in Go.

One possible issue I have is the ability to reliably process messages. I'd like
to be able guarantee that I don't commit an offset before I've positively
confirmed that all of the corresponded messages have been processed
successfully (i.e. not just passed into the processing code, but successfully
completed the associated application-level processing). IIUC the current
API doesn't support this. After you receive an event from the `cg.Stream()`,
the corresponding offset could be committed by the client at any time in the
background.

Do I understand this correctly? If so, is reliable processing something that
you'd be interested in supporting in the high-level API?

**Comment by mihasya** [comment]
I have just arrived at this same point - realizing that the current `consumergroup` implementation commits the offsets independently of processing success.

As far API preferences, I was looking at #20 and it looks like you're defining a map of topics to processing functions - this would work great for us. In fact, we've implemented some code on top of `consumergroup` which works that way, but obviously doesn't have access to the offsets. It's even crossed my mind to use a short-term hack and set the `CommitInterval` to something impossibly long (basically so that `consumergroup` itself never commits) and move the commit logic into the processor function itself.

Are you actively working on #20 still? Do you have any thoughts on what's left before making that branch a reality? Would love to help make this happen.

**Comment by wvanbergen** [comment]
Not working on it due to shifted priorities. Feel free to take it over if you're interested in this; I am available to help.

I primarily was unsure about what API would be most appropriate: using a callback function to process messages, or do something with channels.The implementation shouldn't bee too hard I think once that is figured out. I would say: pick the one you like most and see how far you get.

**Comment by joestein** [comment]
We built an "at least once processing" guarantee consumer over Sarama (along with other real world high level consumer features) https://github.com/stealthly/go_kafka_client if you don't need the other features maybe you could work our implementation for your needs into here or use as is.

**Comment by wvanbergen** [comment]
I implemented this in #30. Any feedback would be appreciated!

**Comment by wvanbergen** [comment]
This is now on master; I'd appreciate any feedback.
